id: org.luoxin971.personal
version: 0.1.0
name: 自用插件
author: luoxin971
ffmpeg_path: "ffmpeg"
silkenc_path: "silk_v3_encoder"
adddefault: true
amrqualityshift: false
amrwb: true
use_custom_ffmpeg_command: false
custom_ffmpeg_command: "ffmpeg -i %input% -ab 23.85k -ar 16000 -ac 1 -acodec amr_wb -y %output%"
enable_local: false
verbose: true
hintsongnotfound: "无法找到歌曲。"
hintcarderror: "分享歌曲失败。"
hintnotemplate: "无法找到卡片。"
hintsourcenotfound: "无法找到来源。"
enableParser: 1
admins:
  - 0
extracommands:
  "#分享":
    source: all
    card: Share

